### ISSUE TITLE
Java 11 and later - Process.setWorkingDirectory() has inconsistent behavior

### ISSUE THREAD

**Issue by tha2015** [gradle/native-platform#113]
On macOS High Sierra and CentOS 7 (not sure about other OSes), the same code snippet will print different values on Java < 11 and Java >= 11
```
        Process p = Native.get(Process.class);

        System.out.println("Setting working dir to /");
        p.setWorkingDirectory(new File("/"));

        System.out.println(new File("build.gradle").exists());
        System.out.println(new File(new File("build.gradle").getAbsolutePath()).exists());
```
On Java 8, it will print: false false (i.e. working directory was changed successfully)
On Java 11, it will print: false true (i.e. working directory was NOT changed correctly)

To reproduce the issue: Unzip the attached zip file  and run below commands (make sure to cd into project directory before running "gradlew run")
[gradle-native.zip](https://github.com/gradle/native-platform/files/4238816/gradle-native.zip)

```
$ cd gradle-native/
$ ./gradlew run

> Task :run
Setting working dir to /
false
true
```

**Comment by blindpirate** [comment]
In pre-11 JDK, there's an internal variable storing working directory, that's why we can change it. After JDK 11 that variable was removed. I submitted this issue to OpenJDK team and got the answer "a process's working directory should not be changed after it starts" (sorry, can't find the issue). So there's nothing we can do, sorry.
